version: '3.7'

services:

  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_HOST=${DB_HOST}
      - PGDATA=/var/lib/postgresql/data/pgdata

# cargo will try to redownload packages @ docker-compose up so store them here.
volumes:
  pgdata: {}
